export const SKILLS_TYPES = {
  FETCH_SKILLS_START: 'FETCH_SKILLS_START',
  FETCH_SKILLS_SUCCESS: 'FETCH_SKILLS_SUCCESS',
  FETCH_SKILLS_FAILURE: 'FETCH_SKILLS_FAILURE',
  
  FETCH_SKILLS_STATS_START: 'FETCH_SKILLS_STATS_START',
  FETCH_SKILLS_STATS_SUCCESS: 'FETCH_SKILLS_STATS_SUCCESS',
  FETCH_SKILLS_STATS_FAILURE: 'FETCH_SKILLS_STATS_FAILURE',
  
  ADD_SKILL: 'ADD_SKILL',
  UPDATE_SKILL: 'UPDATE_SKILL',
  REMOVE_SKILL: 'REMOVE_SKILL',
  
  SET_SKILLS_FILTER: 'SET_SKILLS_FILTER',
  CLEAR_SKILLS: 'CLEAR_SKILLS'
};
